spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://db:5432/springboot_starter
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    defaultModelsExpandDepth: -1
