version: '3.8'

services:
  app:
    image: kotlin-springboot-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springboot_starter
      SPRING_DATASOURCE_USERNAME: your_db_username
      SPRING_DATASOURCE_PASSWORD: your_db_password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: springboot_starter
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - springboot_starter_data:/var/lib/postgresql/data

volumes:
  springboot_starter_data:
